name: intermediate_example
description: Intermediate level demo app
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_mastery_bootcamp_intermediate:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
